" Leader
let mapleader = " "
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
Plugin 'ascenator/L9', {'name': 'newL9'}
Plugin 'xuhdev/vim-latex-live-preview'
Plugin 'sheerun/vim-wombat-scheme'
Plugin 'lervag/vimtex'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-scripts/Wombat'
Plugin 'tomasr/molokai'
Plugin 'dikiaap/minimalist'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'https://github.com/vim-latex/vim-latex.git'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
"Plugin 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
"Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
"Plugin 'lervag/vimtex'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
":PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to
"auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

syntax on
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent

filetype plugin on
let g:tex_flavor='latex'

"set textwidth=80
"set hlsearch
set ignorecase
set number
set relativenumber
set foldmethod=syntax

" colorscheme
"colorscheme koehler
set t_Co=256
colorscheme minimalist
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=#242424

set splitbelow
set splitright
set mouse=a
" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

nnoremap <leader>t :NERDTreeToggle<CR> 
"nnoremap <F12> :NERDTreeToggle<CR> 
"python3 from powerline.vim import setup as powerline_setup
"python3 powerline_setup()
"python3 del powerline_setup

"recompile latex in background upon saving
autocmd BufWritePost *.tex :silent exec '!pdflatex -interaction nonstopmode % > /dev/null'  | redraw!


